---
volumes:
  pihole-data: {}

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0 #latest v5 image
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - "pihole-data:/etc/pihole"
    restart: unless-stopped
