apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.10.100-10.10.10.110 # Replace with an available IP range in your network
